version: "3.8"

services:
    app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_NAME: ecommerce
            DB_USER: root
            DB_PASS: root

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./infrastructure/mysql:/docker-entrypoint-initdb.d/:ro

volumes:
    db_data:
